networks:
  backend:
    attachable: true
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: ${BACKEND_ENABLE_IPV6}
    ipam:
      config:
        - subnet: ${BACKEND_SUBNET}
      driver: ${BACKEND_NETWORK_DRIVER}
  database:
    attachable: true
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: ${DATABASE_NETWORK_ENABLE_IPV6}
    ipam:
      driver: ${DATABASE_NETWORK_DRIVER}
  frontend:
    attachable: true
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: ${FRONTEND_ENABLE_IPV6}
    ipam:
      config:
        - subnet: ${FRONTEND_SUBNET}
      driver: ${FRONTEND_NETWORK_DRIVER}
  tools_frontend:
    attachable: true
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: ${ADD_TOOLS_ENABLE_IPV6}
    ipam:
      config:
        - subnet: ${ADD_TOOLS_SUBNET}
      driver: ${ADD_TOOLS_NETWORK_DRIVER}
secrets:
  MYSQL_PASSWORD:
    file: /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.MYSQL_ROOT_PASSWORD
  MYSQL_ROOT_USER:
    file: /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.MYSQL_ROOT_USER
  MYSQL_USER:
    file: /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.MYSQL_USER
services:
  db-data-mysql:
    image: busybox
    networks:
      - default
    volumes:
      - -var-lib-mysql:/var/lib/mysql
  grafana:
    container_name: grafana
    depends_on:
      - zabbix-server
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_grafana
    image: grafana/grafana
    networks:
      - default
    ports:
      - ${GRAFANA_PORT}:3000
    restart: ${RESTART_POLICY}
    user: root
    volumes:
      - -var-lib-grafana:/var/lib/grafana
  mysql-server:
    command:
      - mysqld
      - --skip-mysqlx
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --log_bin_trust_function_creators=1
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_db_mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
    image: ${MYSQL_IMAGE}:${MYSQL_IMAGE_TAG}
    networks:
      - database
    restart: ${RESTART_POLICY}
    secrets:
      - source: MYSQL_USER
        target: /run/secrets/MYSQL_USER
      - source: MYSQL_PASSWORD
        target: /run/secrets/MYSQL_PASSWORD
      - source: MYSQL_ROOT_PASSWORD
        target: /run/secrets/MYSQL_ROOT_PASSWORD
    stop_grace_period: 1m
    volumes:
      - -var-lib-mysql:/var/lib/mysql
  selenium:
    image: ${WEBDRIVER_IMAGE}:${WEBDRIVER_IMAGE_TAG}
    networks:
      - tools_frontend
  selenium-chrome:
    depends_on:
      - selenium
    deploy:
      replicas: 2
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_selenium_chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    image: ${WEBDRIVER_CHROME_IMAGE}:${WEBDRIVER_CHROME_IMAGE_TAG}
    networks:
      - tools_frontend
    restart: ${RESTART_POLICY}
    shm_size: 2gb
  selenium-firefox:
    depends_on:
      - selenium
    deploy:
      replicas: 2
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_selenium_firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    image: ${WEBDRIVER_FIREFOX_IMAGE}:${WEBDRIVER_FIREFOX_IMAGE_TAG}
    networks:
      - tools_frontend
    restart: ${RESTART_POLICY}
    shm_size: 2gb
  zabbix-agent:
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_agent
    image: ${ZABBIX_AGENT_IMAGE}:${ZABBIX_OL_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}
    labels:
      - com.zabbix.company=Zabbix LLC
      - com.zabbix.component=zabbix-agentd
      - com.zabbix.description=Zabbix agent
      - com.zabbix.os=${OL_OS_TAG}
    networks:
      - backend
    pid: host
    ports:
      - target: 10050
        published: ${ZABBIX_AGENT_PORT}
        protocol: tcp
        mode: host
    privileged: true
    restart: ${RESTART_POLICY}
    stop_grace_period: 5s
    tmpfs:
      - /tmp
    volumes:
      - -etc-zabbix-zabbix_agentd-d:/etc/zabbix/zabbix_agentd.d:ro
      - -var-lib-zabbix-modules:/var/lib/zabbix/modules:ro
      - -var-lib-zabbix-enc:/var/lib/zabbix/enc:ro
      - -var-lib-zabbix-ssh_keys:/var/lib/zabbix/ssh_keys:ro
  zabbix-java-gateway:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_java
    image: ${ZABBIX_JAVA_GATEWAY_IMAGE}:${ZABBIX_OL_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}
    labels:
      - com.zabbix.company=Zabbix LLC
      - com.zabbix.component=java-gateway
      - com.zabbix.description=Zabbix Java Gateway
      - com.zabbix.os=${OL_OS_TAG}
    networks:
      - backend
      - frontend
    ports:
      - ${ZABBIX_JAVA_GATEWAY_PORT}:10052
    restart: ${RESTART_POLICY}
    stop_grace_period: 5s
  zabbix-proxy-sqlite3:
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 512M
        reservations:
          cpus: "0.3"
          memory: 256M
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_prx
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_prx_sqlite3
    image: ${ZABBIX_PROXY_SQLITE3_IMAGE}:${ZABBIX_OL_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}
    labels:
      - com.zabbix.company=Zabbix LLC
      - com.zabbix.component=zabbix-proxy
      - com.zabbix.dbtype=sqlite3
      - com.zabbix.description=Zabbix proxy with SQLite3 database support
      - com.zabbix.os=${OL_OS_TAG}
    networks:
      - backend
      - frontend
      - tools_frontend
    ports:
      - ${ZABBIX_PROXY_SQLITE3_PORT}:10051
    restart: ${RESTART_POLICY}
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        hard: 40000
        soft: 20000
      nproc: 65535
    volumes:
      - -usr-lib-zabbix-externalscripts:/usr/lib/zabbix/externalscripts:ro
      - -var-lib-zabbix-modules:/var/lib/zabbix/modules:ro
      - -var-lib-zabbix-enc:/var/lib/zabbix/enc:ro
      - -var-lib-zabbix-ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - -var-lib-zabbix-mibs:/var/lib/zabbix/mibs:ro
  zabbix-server:
    depends_on:
      - mysql-server
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_srv
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_db_mysql
    image: ${ZABBIX_SERVER_MYSQL_IMAGE}:${ZABBIX_OL_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}
    labels:
      - com.zabbix.company=Zabbix LLC
      - com.zabbix.component=zabbix-server
      - com.zabbix.dbtype=mysql
      - com.zabbix.description=Zabbix server with MySQL database support
      - com.zabbix.os=${OL_OS_TAG}
    networks:
      - backend
      - database
      - frontend
      - tools_frontend
    ports:
      - target: 10051
        published: ${ZABBIX_SERVER_PORT}
        protocol: tcp
        mode: host
    restart: ${RESTART_POLICY}
    secrets:
      - source: MYSQL_USER
        target: /run/secrets/MYSQL_USER
      - source: MYSQL_PASSWORD
        target: /run/secrets/MYSQL_PASSWORD
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        hard: 40000
        soft: 20000
      nproc: 65535
    volumes:
      - -usr-lib-zabbix-alertscripts:/usr/lib/zabbix/alertscripts:ro
      - -usr-lib-zabbix-externalscripts:/usr/lib/zabbix/externalscripts:ro
      - -var-lib-zabbix-dbscripts:/var/lib/zabbix/dbscripts:ro
      - -var-lib-zabbix-export:/var/lib/zabbix/export
      - -var-lib-zabbix-modules:/var/lib/zabbix/modules:ro
      - -var-lib-zabbix-enc:/var/lib/zabbix/enc:ro
      - -var-lib-zabbix-ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - -var-lib-zabbix-mibs:/var/lib/zabbix/mibs:ro
  zabbix-snmptraps:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_snmptraps
    image: ${ZABBIX_SNMPTRAPS_IMAGE}:${ZABBIX_OL_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}
    labels:
      - com.zabbix.company=Zabbix LLC
      - com.zabbix.component=snmptraps
      - com.zabbix.description=Zabbix snmptraps
      - com.zabbix.os=${OL_OS_TAG}
    networks:
      - backend
      - frontend
    ports:
      - ${ZABBIX_SNMPTRAPS_PORT}:1162/udp
    read_only: true
    restart: ${RESTART_POLICY}
    stop_grace_period: 5s
    tmpfs:
      - /tmp
    volumes: []
  zabbix-web-nginx-mysql:
    depends_on:
      - mysql-server
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_web
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_db_mysql
    healthcheck:
      interval: 10s
      retries: 3
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/ping
      timeout: 5s
    image: ${ZABBIX_WEB_NGINX_MYSQL_IMAGE}:${ZABBIX_OL_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}
    labels:
      - com.zabbix.company=Zabbix LLC
      - com.zabbix.component=zabbix-frontend
      - com.zabbix.webserver=nginx
      - com.zabbix.dbtype=mysql
      - com.zabbix.description=Zabbix frontend on Nginx web-server with MySQL database
        support
      - com.zabbix.os=${OL_OS_TAG}
    networks:
      - backend
      - database
      - frontend
    ports:
      - ${ZABBIX_WEB_NGINX_HTTP_PORT}:8080
      - ${ZABBIX_WEB_NGINX_HTTPS_PORT}:8443
    restart: ${RESTART_POLICY}
    secrets:
      - source: MYSQL_USER
        target: /run/secrets/MYSQL_USER
      - source: MYSQL_PASSWORD
        target: /run/secrets/MYSQL_PASSWORD
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    tmpfs:
      - /tmp
    volumes:
      - -etc-ssl-nginx:/etc/ssl/nginx:ro
      - -usr-share-zabbix-modules:/usr/share/zabbix/modules:ro
  zabbix-web-service:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    env_file:
      - /opt/zabbix-docker/${ENV_VARS_DIRECTORY}/.env_web_service
    image: ${ZABBIX_WEB_SERVICE_IMAGE}:${ZABBIX_OL_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}
    labels:
      - com.zabbix.company=Zabbix LLC
      - com.zabbix.component=web-service
      - com.zabbix.description=Zabbix web service
      - com.zabbix.os=${OL_OS_TAG}
    networks:
      - backend
    ports:
      - ${ZABBIX_WEB_SERVICE_PORT}:10053
    restart: ${RESTART_POLICY}
    security_opt:
      - seccomp:${ENV_VARS_DIRECTORY}/chrome_dp.json
    stop_grace_period: 5s
    tmpfs:
      - /tmp
    volumes:
      - -var-lib-zabbix-enc:/var/lib/zabbix/enc:ro
version: "3.3"
volumes:
  -etc-ssl-nginx:
    driver: local
  -etc-zabbix-zabbix_agentd-d:
    driver: local
  -usr-lib-zabbix-alertscripts:
    driver: local
  -usr-lib-zabbix-externalscripts:
    driver: local
  -usr-share-zabbix-modules:
    driver: local
  -var-lib-grafana:
    driver: local
  -var-lib-mysql:
    driver: local
  -var-lib-zabbix-dbscripts:
    driver: local
  -var-lib-zabbix-enc:
    driver: local
  -var-lib-zabbix-export:
    driver: local
  -var-lib-zabbix-mibs:
    driver: local
  -var-lib-zabbix-modules:
    driver: local
  -var-lib-zabbix-ssh_keys:
    driver: local
  snmptraps:
    driver: local
